### ISSUE TITLE
Wrapping images and paragraphs in container div to have text below images (featured teas)

### ISSUE THREAD

**Issue by griffinlacek** [justingould76/prj-rev-bwfs-tea-cozy#5]
Just a suggestion on how you might be able to accomplish having your featured tea text be below the images like the spec has.

If you wrap the img and p in a div like this:

```
<div class="tea-item">
    <img id="pics" src="./resources/img-berryblitz.jpg">
     <p>Fall Berry Blitz</p>
</div>
```

And then add these styles to make each div items a flex box that flows in a column:

```
.tea-item {
  display: flex;
  flex-direction: column;
}

Then you'd have separated featured teas that flow like the spec does!

https://github.com/justingould76/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/index.html#L27-L36

**Comment by justingould76** [comment]
Thank You so much for this one...really wracked my brain and searched everywhere!!
